// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance_query.sql

package balancerepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBalance = `-- name: CreateBalance :exec
INSERT INTO public.balance(id, balance, user_id)
	VALUES ($1, $2, $3)
`

type CreateBalanceParams struct {
	ID      int64
	Balance pgtype.Numeric
	UserID  int64
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) error {
	_, err := q.db.Exec(ctx, createBalance, arg.ID, arg.Balance, arg.UserID)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT id, balance, user_id
	FROM public.balance
	where user_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, userID int64) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var i Balance
	err := row.Scan(&i.ID, &i.Balance, &i.UserID)
	return i, err
}

const getWithdrawals = `-- name: GetWithdrawals :many
SELECT order_num, withdraw_amount, user_id, created_at
	FROM public.withdraw_history
	where user_id = $1
`

type GetWithdrawalsRow struct {
	OrderNum       int64
	WithdrawAmount pgtype.Numeric
	UserID         int64
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) GetWithdrawals(ctx context.Context, userID int64) ([]GetWithdrawalsRow, error) {
	rows, err := q.db.Query(ctx, getWithdrawals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWithdrawalsRow
	for rows.Next() {
		var i GetWithdrawalsRow
		if err := rows.Scan(
			&i.OrderNum,
			&i.WithdrawAmount,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWithdrawal = `-- name: InsertWithdrawal :exec
INSERT INTO public.withdraw_history(order_num, withdraw_amount, user_id)
	VALUES ($1, $2, $3)
`

type InsertWithdrawalParams struct {
	OrderNum       int64
	WithdrawAmount pgtype.Numeric
	UserID         int64
}

func (q *Queries) InsertWithdrawal(ctx context.Context, arg InsertWithdrawalParams) error {
	_, err := q.db.Exec(ctx, insertWithdrawal, arg.OrderNum, arg.WithdrawAmount, arg.UserID)
	return err
}

const tryDecreaseBalance = `-- name: TryDecreaseBalance :one
WITH updated AS (
	UPDATE public.balance
	SET balance = balance - $2
	WHERE user_id = $1
	  AND balance >= $2
	RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM updated) AS decreased
`

type TryDecreaseBalanceParams struct {
	UserID  int64
	Balance pgtype.Numeric
}

func (q *Queries) TryDecreaseBalance(ctx context.Context, arg TryDecreaseBalanceParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryDecreaseBalance, arg.UserID, arg.Balance)
	var decreased bool
	err := row.Scan(&decreased)
	return decreased, err
}
