// Code generated by MockGen. DO NOT EDIT.
// Source: order_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	orderrepository "avgys-gophermat/sqlc/order"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// GetOrAddEmptyOrder mocks base method.
func (m *MockOrderRepository) GetOrAddEmptyOrder(ctx context.Context, params *orderrepository.GetOrAddOrderParams) (orderrepository.GetOrAddOrderRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrAddEmptyOrder", ctx, params)
	ret0, _ := ret[0].(orderrepository.GetOrAddOrderRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrAddEmptyOrder indicates an expected call of GetOrAddEmptyOrder.
func (mr *MockOrderRepositoryMockRecorder) GetOrAddEmptyOrder(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrAddEmptyOrder", reflect.TypeOf((*MockOrderRepository)(nil).GetOrAddEmptyOrder), ctx, params)
}

// GetOrdersByUser mocks base method.
func (m *MockOrderRepository) GetOrdersByUser(ctx context.Context, userID int64) ([]orderrepository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUser", ctx, userID)
	ret0, _ := ret[0].([]orderrepository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUser indicates an expected call of GetOrdersByUser.
func (mr *MockOrderRepositoryMockRecorder) GetOrdersByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUser", reflect.TypeOf((*MockOrderRepository)(nil).GetOrdersByUser), ctx, userID)
}

// GetUnproccessedOrders mocks base method.
func (m *MockOrderRepository) GetUnproccessedOrders(ctx context.Context, limit int32) ([]orderrepository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnproccessedOrders", ctx, limit)
	ret0, _ := ret[0].([]orderrepository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnproccessedOrders indicates an expected call of GetUnproccessedOrders.
func (mr *MockOrderRepositoryMockRecorder) GetUnproccessedOrders(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnproccessedOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetUnproccessedOrders), ctx, limit)
}

// UpdateOrderAndIncreaseBalance mocks base method.
func (m *MockOrderRepository) UpdateOrderAndIncreaseBalance(ctx context.Context, arg *orderrepository.UpdateOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderAndIncreaseBalance", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderAndIncreaseBalance indicates an expected call of UpdateOrderAndIncreaseBalance.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderAndIncreaseBalance(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderAndIncreaseBalance", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderAndIncreaseBalance), ctx, arg)
}
