// Code generated by MockGen. DO NOT EDIT.
// Source: accrual_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	responses "avgys-gophermat/internal/model/responses"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccrualClient is a mock of AccrualClient interface.
type MockAccrualClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientMockRecorder
}

// MockAccrualClientMockRecorder is the mock recorder for MockAccrualClient.
type MockAccrualClientMockRecorder struct {
	mock *MockAccrualClient
}

// NewMockAccrualClient creates a new mock instance.
func NewMockAccrualClient(ctrl *gomock.Controller) *MockAccrualClient {
	mock := &MockAccrualClient{ctrl: ctrl}
	mock.recorder = &MockAccrualClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClient) EXPECT() *MockAccrualClientMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockAccrualClient) Send(ctx context.Context, orderNum string) (*responses.AccrualOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, orderNum)
	ret0, _ := ret[0].(*responses.AccrualOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockAccrualClientMockRecorder) Send(ctx, orderNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAccrualClient)(nil).Send), ctx, orderNum)
}
