// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	responses "avgys-gophermat/internal/model/responses"
	auth "avgys-gophermat/internal/service/auth"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// GetOrderByUserID mocks base method.
func (m *MockOrderService) GetOrderByUserID(ctx context.Context, userClaims *auth.TokenClaims) ([]responses.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByUserID", ctx, userClaims)
	ret0, _ := ret[0].([]responses.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByUserID indicates an expected call of GetOrderByUserID.
func (mr *MockOrderServiceMockRecorder) GetOrderByUserID(ctx, userClaims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByUserID", reflect.TypeOf((*MockOrderService)(nil).GetOrderByUserID), ctx, userClaims)
}

// Store mocks base method.
func (m *MockOrderService) Store(ctx context.Context, userClaims *auth.TokenClaims, orderNum string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userClaims, orderNum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockOrderServiceMockRecorder) Store(ctx, userClaims, orderNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockOrderService)(nil).Store), ctx, userClaims, orderNum)
}
