// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_query.sql

package userrepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO public.users(login, hash_salt, password_hash)
VALUES ($1, $2, $3)
RETURNING Id
`

type CreateUserParams struct {
	Login        string
	HashSalt     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.HashSalt, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT login, hash_salt, password_hash, created_at 
FROM public.users
where login = $1
`

type GetUserByLoginRow struct {
	Login        string
	HashSalt     string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.Login,
		&i.HashSalt,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
