// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	responses "avgys-gophermat/internal/model/responses"
	orderrepository "avgys-gophermat/sqlc/order"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// GetOrderUnprocessedOrders mocks base method.
func (m *MockOrderService) GetOrderUnprocessedOrders(ctx context.Context, limit int) ([]orderrepository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderUnprocessedOrders", ctx, limit)
	ret0, _ := ret[0].([]orderrepository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderUnprocessedOrders indicates an expected call of GetOrderUnprocessedOrders.
func (mr *MockOrderServiceMockRecorder) GetOrderUnprocessedOrders(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderUnprocessedOrders", reflect.TypeOf((*MockOrderService)(nil).GetOrderUnprocessedOrders), ctx, limit)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderService) UpdateOrderStatus(ctx context.Context, accrualOrder *responses.AccrualOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, accrualOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderServiceMockRecorder) UpdateOrderStatus(ctx, accrualOrder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderStatus), ctx, accrualOrder)
}
