CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    login VARCHAR(255) NOT NULL UNIQUE,
    hash VARCHAR(255) NOT NULL,
    password_hash BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);