// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_query.sql

package orderrepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrAddOrder = `-- name: GetOrAddOrder :one
WITH inserted AS (
	INSERT INTO public.orders(
		order_num, status, accrual, user_id)
		VALUES ($1, $2, $3, $4)
	ON CONFLICT (order_num) DO NOTHING
	RETURNING order_num, status, accrual, user_id, created_at
)
SELECT order_num, status, accrual, user_id, created_at, true as is_new
FROM inserted
UNION ALL
SELECT order_num, status, accrual, user_id, created_at, false as is_new
FROM orders
WHERE order_num = $1
  AND NOT EXISTS (SELECT 1 FROM inserted)
`

type GetOrAddOrderParams struct {
	OrderNum int64
	Status   int32
	Accrual  pgtype.Numeric
	UserID   int64
}

type GetOrAddOrderRow struct {
	OrderNum  int64
	Status    int32
	Accrual   pgtype.Numeric
	UserID    int64
	CreatedAt pgtype.Timestamp
	IsNew     bool
}

func (q *Queries) GetOrAddOrder(ctx context.Context, arg GetOrAddOrderParams) (GetOrAddOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrAddOrder,
		arg.OrderNum,
		arg.Status,
		arg.Accrual,
		arg.UserID,
	)
	var i GetOrAddOrderRow
	err := row.Scan(
		&i.OrderNum,
		&i.Status,
		&i.Accrual,
		&i.UserID,
		&i.CreatedAt,
		&i.IsNew,
	)
	return i, err
}

const getOrdersByUser = `-- name: GetOrdersByUser :many
SELECT order_num, status, accrual, user_id, created_at
	FROM orders
	where user = $1
`

func (q *Queries) GetOrdersByUser(ctx context.Context, dollar_1 interface{}) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderNum,
			&i.Status,
			&i.Accrual,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnproccessedOrders = `-- name: GetUnproccessedOrders :many
SELECT order_num, status, accrual, user_id, created_at
	FROM orders
	where status IN (0, 1)
`

func (q *Queries) GetUnproccessedOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getUnproccessedOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderNum,
			&i.Status,
			&i.Accrual,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
